// coins.js
const coins = [
    { id: 'aave', name: 'AAVE Wallet', imageUrl: 'img/icn-aave-wallet.png' },
{ id: 'argent', name: 'Argent', imageUrl: 'img/argent.jpg' },
{ id: 'arculus', name: 'Arculus', imageUrl: 'img/arculus.jpg.png' },
{ id: 'atomic', name: 'Atomic Wallet', imageUrl: 'img/atomic.jpg' },
{ id: 'atoken_wallet', name: 'AToken Wallet', imageUrl: 'img/atoken_wallet.jpg' },
{ id: 'at_wallet', name: 'AT.Wallet', imageUrl: 'img/at_wallet.jpg' },
{ id: 'auth', name: 'Authereum', imageUrl: 'img/icn-authereum.svg' },
{ id: 'bifrost', name: 'Bifrost Wallet', imageUrl: 'img/bifrost.jpg' },
{ id: 'binance', name: 'Binance Chain Wallet', imageUrl: 'img/icn-binance-smart-chain.png' },
{ id: 'bitkeep', name: 'BitKeep', imageUrl: 'img/bitkeep.jpg' },
{ id: 'bitpay', name: 'Bitpay', imageUrl: 'img/bitpay-1573dd6c95eb38386f181048663590d0.jpg' },
{ id: 'blockchain', name: 'Blockchain', imageUrl: 'img/blockchain-logo.png' },
{ id: 'bridgewallet', name: 'Bridge Wallet', imageUrl: 'img/bridge_wallet.jpg' },
{ id: 'celowallet', name: 'Cello Wallet', imageUrl: 'img/celo_wallet.jpg' },
{ id: 'coin98', name: 'Coin98', imageUrl: 'img/coin98.jpg' },
{ id: 'coinbase', name: 'Coinbase', imageUrl: 'img/icn-coinbase.svg' },
{ id: 'coinmoni', name: 'Coinomi Wallet', imageUrl: 'img/icn-coinmoni-wallet.png' },
{ id: 'coinus', name: 'CoinUs', imageUrl: 'img/coinus.jpg' },
{ id: 'compound', name: 'Compound', imageUrl: 'img/compound.jpg' },
{ id: 'coolwall', name: 'CoolWallet', imageUrl: 'img/cool_wallet_s.jpg' },
{ id: 'cryptocom', name: 'Crypto.com', imageUrl: 'img/crypto-4cbeac57421fb3ca2573db2cf448169a.png' },
{ id: 'dharma', name: 'Dharma', imageUrl: 'img/dharma.jpg' },
{ id: 'digitex', name: 'Digitex', imageUrl: 'img/icn-digitx-wallet.png' },
{ id: 'dokwallet', name: 'Dok Wallet', imageUrl: 'img/dok_wallet.jpg' },
{ id: 'easypocket', name: 'EasyPocket', imageUrl: 'img/easypocket.jpg' },
{ id: 'eidoo', name: 'Eidoo Wallet', imageUrl: 'img/icn-eidoo-wallet.png' },
{ id: 'ellipal', name: 'Ellipal', imageUrl: 'img/ellipal.jpg.png' },
{ id: 'enjin', name: 'Enjin Wallet', imageUrl: 'img/icn-enjin-wallet.png' },
{ id: 'etoro', name: 'Etoro Wallet', imageUrl: 'img/etoro.jpg.png' },
{ id: 'exodus', name: 'Exodus Wallet', imageUrl: 'img/exodus.jpeg' },
{ id: 'flare_wallet', name: 'Flare Wallet', imageUrl: 'img/flare_wallet.jpg' },
{ id: 'formatic', name: 'Formatic', imageUrl: 'img/icn-formatic.png' },
{ id: 'guardawallet', name: 'Gaurda Wallet', imageUrl: 'img/guarda_wallet.jpg' },
{ id: 'gridplus', name: 'GridPlus', imageUrl: 'img/gridplus.jpg' },
{ id: 'halodefiwallet', name: 'HaloDefi Wallet', imageUrl: 'img/halodefi_wallet.jpg' },
{ id: 'hashkey_me', name: 'HashKey Me', imageUrl: 'img/hashkey_me.jpg' },
{ id: 'hiro', name: 'Hiro Wallet', imageUrl: 'img/hiro.jpeg' },
{ id: 'huobi', name: 'Huobi Wallet', imageUrl: 'img/huobi.jpg' },
{ id: 'imtoken', name: 'imToken', imageUrl: 'img/imtoken.jpg' },
{ id: 'inch', name: '1Inch', imageUrl: 'img/1inch.jpg' },
{ id: 'infinito', name: 'Infinito Wallet', imageUrl: 'img/infinito.jpg' },
{ id: 'jadewallet', name: 'Jade Wallet', imageUrl: 'img/jade_wallet.jpg' },
{ id: 'keyring_pro', name: 'KEYRING PRO', imageUrl: 'img/keyring_pro.jpg' },
{ id: 'kucoin', name: 'Kucoin Wallet', imageUrl: 'img/kucoin.png' },
{ id: 'kyberswap', name: 'KyberSwap', imageUrl: 'img/kyberswap.jpg' },
{ id: 'leather', name: 'Leather Wallet', imageUrl: 'img/leather.jpeg' },
{ id: 'ledger', name: 'Ledger', imageUrl: 'img/icn-ledger.svg' },
{ id: 'math', name: 'Math Wallet', imageUrl: 'img/math_wallet.jpg' },
{ id: 'meta', name: 'Metamask', imageUrl: 'img/icn-meta-mask.svg' },
{ id: 'midas_wallet', name: 'Midas Wallet', imageUrl: 'img/midas_wallet.jpg' },
{ id: 'monero', name: 'Monero Wallet', imageUrl: 'img/icn-monero-wallet.png' },
{ id: 'mykey', name: 'MYKEY', imageUrl: 'img/mykey.jpg' },
{ id: 'nash', name: 'Nash', imageUrl: 'img/nash.jpg' },
{ id: 'o3wallet', name: 'O3Wallet', imageUrl: 'img/o3_wallet.jpg' },
{ id: 'okx', name: 'OKX Wallet', imageUrl: 'img/okx.png' },
{ id: 'onto', name: 'ONTO', imageUrl: 'img/onto.jpg.png' },
{ id: 'ownbit', name: 'Ownbit', imageUrl: 'img/ownbit.jpg' },
{ id: 'phantom', name: 'Phantom', imageUrl: 'img/phantom.webp' },
{ id: 'plasmapay', name: 'PlasmaPay', imageUrl: 'img/plasmapay.jpg' },
{ id: 'pol', name: 'Polkadot', imageUrl: 'img/pol.png' },
{ id: 'polygon', name: 'Polygon Wallet', imageUrl: 'img/polygon.jpg' },
{ id: 'portis', name: 'Portis', imageUrl: 'img/icn-portis.png' },
{ id: 'protocol', name: 'Protocol', imageUrl: 'img/icn-protocol.png' },
{ id: 'rainbow', name: 'Rainbow Wallet', imageUrl: 'img/rainbow.jpg' },
{ id: 'ronin', name: 'Ronin', imageUrl: 'img/ronin.png' },
{ id: 'rwallet', name: 'RWallet', imageUrl: 'img/rwallet.jpg' },
{ id: 'safepal', name: 'SafePal', imageUrl: 'img/safepal.jpg' },
{ id: 'solana', name: 'Solana', imageUrl: 'img/solana.png' },
{ id: 'spatium', name: 'Spatium', imageUrl: 'img/spatium.jpg.png' },
{ id: 'squarelink', name: 'Squarelink', imageUrl: 'img/icn-squarelink.png' },
{ id: 'talken_wallet', name: 'Talken Wallet', imageUrl: 'img/talken_wallet.jpg' },
{ id: 'tongue_wallet', name: 'Tongue Wallet', imageUrl: 'img/tongue_wallet.jpg' },
{ id: 'tokenpocket', name: 'Token Pocket', imageUrl: 'img/icn-token-pocket.jpg' },
{ id: 'torus', name: 'Tirus', imageUrl: 'img/torus.jpg' },
{ id: 'tradestation', name: 'Tradestation', imageUrl: 'img/tradestation.jpg.png' },
{ id: 'trezor', name: 'Trezor', imageUrl: 'img/trezor.jpg.png' },
{ id: 'trust', name: 'TrustWallet', imageUrl: 'img/icn-trust-wallet.png' },
{ id: 'trustee_wallet', name: 'Trustee Wallet', imageUrl: 'img/trustee_wallet.jpg' },
{ id: 'trustv', name: 'Trust Vault', imageUrl: 'img/trust_vault.jpg' },
{ id: 'unisat', name: 'Unisat Wallet', imageUrl: 'img/unisat.jpeg' },
{ id: 'unstoppablewallet', name: 'Unstoppable Wallet', imageUrl: 'img/unstoppable_wallet.jpg' },
{ id: 'valora', name: 'Valora', imageUrl: 'img/valora.jpg' },
{ id: 'viawallet', name: 'ViaWallet', imageUrl: 'img/via_wallet.jpg' },
{ id: 'walletconnect', name: 'Wallet Connect', imageUrl: 'img/walle.jpg' },
{ id: 'walleth', name: 'Walleth', imageUrl: 'img/walleth.jpg' },
{ id: 'walletio', name: 'Wallet.io', imageUrl: 'img/wallet_io.jpg' },
{ id: 'xinfin', name: 'XinFin XDC Network', imageUrl: 'img/xinfin.jpg' },
{ id: 'xumm', name: 'Xumm Wallet', imageUrl: 'img/xumm.jpg' },
{ id: 'xverse', name: 'Xverse Wallet', imageUrl: 'img/xverse.png' },
{ id: 'zelcore', name: 'Zelcore', imageUrl: 'img/zelcore.jpg' },
{ id: 'others', name: 'Others', imageUrl: 'img/undraw_Confirmation_re_b6q5.png' }
];
